behaviors:
  Avoidance:
    trainer_type: ppo
    hyperparameters:
      batch_size: 5120
      buffer_size: 51200
      learning_rate: 0.0002
      beta: 0.003
      epsilon: 0.15
      lambd: 0.93
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.96
        strength: 1.0
    keep_checkpoints: 9999
    max_steps: 80000000
    time_horizon: 1000
    summary_freq: 20000
    checkpoint_interval: 50000
    threaded: true